# Configuration H2 Database (base de donnees en memoire - pas besoin de MySQL/XAMPP)
spring.datasource.url=jdbc:h2:mem:magasin_informatique
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuration Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Console H2 pour voir la base de donnees
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration de logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
